### PR TITLE
Adding sequence, sequence_template, sequence_state, sequence_step tables

### PR DESCRIPTION
**Pull request by DimasOT18**
# Description of change
Added the sequence, sequence_template, sequence_state, sequence_step tables to the STREAM_CONFIGS object in sync.py. Added schemas for each table. 

# Manual QA steps
 - Qa'ed against Outreach Documentation 
 
# Risks
 - Foreign Key relationships based off of table behavior in UI. 
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @DimasOT18, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @DimasOT18!

Thank you for signing the Singer Contribution License Agreement.

**Comment by chrismeier** [comment]
This is an exciting PR @DimasOT18! Hopefully it's on a short list to be reviewed soon. @cmerrick do you have a sense for the timeline of this one?

**Comment by danjsiegel1** [comment]
@cmerrick another vote for prioritizing this one!

**Comment by stkbailey** [comment]
another vote!

**Comment by bigsetch** [comment]
Another vote!

**Comment by stkbailey** [comment]
@cmerrick Is there any way we can get this pushed through?

**Pull request merged**
